### ISSUE TITLE
[feature] inference of hierarchy: query on a term returns term and children

### ISSUE THREAD

**Issue by jibe-b** [gnpis/DataSearch#1]
With a hierarchy of concepts such as:

- A
  - B
  - C

with B and C children of A,

querying A returns A, B and C, as B and C are As too.

**Comment by florian-philippe** [comment]
Voici une première version du RDF : https://urgi.versailles.inra.fr/files/semantic/generic_rdf.n3
En ce qui concerne la hiérarchie et l'inférence, j'ai effectué des tests en java pour vérifier le comportement et tout semble cohérent et fonctionnel.

Le soucis qui se présente est le suivant : le parent A (un id unique) se doit d'être le moins complexe possible afin d'éviter de devoir à échapper les caractères spéciaux et rendre le parsing évident.
Actuellement ce n'est pas tout à fait le cas car on se retrouve parfois avec des parents A relativement complexe (plusieurs caractères spéciaux), ce qui rend le post-traitement plus complexe.

**Comment by jibe-b** [comment]
@florian-philippe As-tu envisagé d'encoder tous les ids?

**Comment by florian-philippe** [comment]
@jibe-b Qu'entends-tu par encoder tous les ids ?
Il est nécessaire de transformer les caractères spéciaux uniquement lors du parsing du rdf via la librairie RDF4J en gwt car sinon le rdf n'est pas considéré comme valide.
Après discussion avec d'autres collègues, il est vrai qu'un travail de curation est à faire en base et résoudrait ainsi cette histoire de complexité.

Je vais continuer l'implémentation côté serveur et voir les performances, ce sera une base de reflexion importante et stratégique pour la suite.
Si il s'agit simplement de revoir le format du RDF, c'est assez secondaire et très facile à mettre en place.

**Comment by jibe-b** [comment]
Je suggérais juste d'aller au-delà de l'encodage des espaces comme dans
`gnpis:Vitis%2Cx%2Cinterspécifique%2Ccv.%2CRudelin%2C5-41` et d'encoder également les caractères spéciaux comme dans
`gnpis:Vitis%20x%20intersp%C3%A9cifique%20cv.%20Rudelin%205-41`.

En revanche, je ne suis pas sûr de bien comprendre le problème, donc ce n'est peut-être pas suffisant.

**Comment by florian-philippe** [comment]
On filtre le modèle avec les fonctions suivantes via la librairie RDF4J : 
```
for (Resource concept: model.filter(null, RDF.TYPE, SKOS.CONCEPT).subjects()){

	if(concept.stringValue().equals(prefix+term_encoded)){

		prefLabel = Models.objectString(model.filter(concept, SKOS.PREF_LABEL, null));

		if(!prefLabel.equals(term)){

			allSynonyms.add(prefLabel);
		}

		for (Statement altLabels : model.filter(concept, SKOS.ALT_LABEL, null)) {
			Value altLabel = altLabels.getObject();
			if(!allSynonyms.contains(altLabel)){
				allSynonyms.add(altLabel.stringValue().toString());
			}
		}
	}				
}
```

Pour récupérer les altLabels + prefLabel associé au userKeyword  de l'utilisateur, il faut pouvoir retrouver le concept associé (qui lui est encodé) alors que le userKeyword non.
Exemple je tape : 
Vitis x interspécifique cv. Rudelin 5-41
Je dois aller chercher le concept dans le RDF N3 : gnpis:Vitis%2Cx%2Cinterspécifique%2Ccv.%2CRudelin%2C5-41

**Comment by florian-philippe** [comment]
```
gnpis:gnpis_pui:unknown:Tomato:CR082	rdf:type skos:Concept;
	skos:prefLabel	"CR082";
	skos:altLabel	"656";
	skos:altLabel	"N° 362 Vishnevidnyi".
```
Pour ce concept suivant, sans caractères spéciaux, le traitement est relativement simple.
Tu vois la différence ?

**Comment by jibe-b** [comment]
@florian-philippe Est-ce que ce soucis a pu être solutionné ?

**Comment by florian-philippe** [comment]
Excuse moi pour le temps de réactivité,
Nous sommes parti sur une approche différente pour résoudre ce soucis et on ne passe plus par l'URI comme point d'entrée de l'arbre.
On parcourt les altLabel et les prefLabel recursivement à partir du keyword et on adopte une approche ascendant/descendant par la même occasion.

**Comment by jibe-b** [comment]
Ok.
Quand la version beta sera mise à jour, je ferai des essais pour tester la hiérarchie et les synonymes.
