### ISSUE TITLE
[bug] conflit entre les paramètres "nombre de résultats" et "type de snippet

### ISSUE THREAD

**Issue by jibe-b** [gnpis/DataSearch#10]
Pour une requête comme [lodging resistance](https://urgi.versailles.inra.fr/wheatis/#result/term=lodging%20resistance),

ajuster les paramètres 
- nombre de résultats par page ![image](https://user-images.githubusercontent.com/6146483/37605662-fbeb9aa2-2b93-11e8-82f6-ca7d78522409.png)
- et "type de snippet"  ![image](https://user-images.githubusercontent.com/6146483/37605753-29d76162-2b94-11e8-9597-f24768ec62a0.png)

 ne peut pas être faite successivement (l'autre paramètre est remis à zéro).

**Comment by raf64flo** [comment]
Je ne parviens pas à reproduire le soucis rencontré. Peux-tu préciser stp ?

**Comment by jibe-b** [comment]
Voici un exemple : 

Note: J'ai essayé de comprendre le fonctionnement de ![image](https://user-images.githubusercontent.com/6146483/37647001-7e7f6042-2c2b-11e8-9cba-95c9107f2758.png) mais je ne suis pas du tout sûr de savoir la logique qui est derrière.


Requête : https://urgi.versailles.inra.fr/wheatis/#result/term=pathogen%20resistance


1. point de départ : (results_per_page=10, snippets=type_0)

![image](https://user-images.githubusercontent.com/6146483/37646964-5c6785c0-2c2b-11e8-854f-944085796706.png)

2. changement du nombre de résultats par page (results_per_page=20, snippets=type_0)

![image](https://user-images.githubusercontent.com/6146483/37647065-a6aacffc-2c2b-11e8-92f8-deefb28ca7f0.png)

3. changement du type de snippet 

devrait être : (results_per_page=20, snippets=type_1)

mais comportement réel : (results_per_page=10, snippets=type_1)

![image](https://user-images.githubusercontent.com/6146483/37647131-d0c4d076-2c2b-11e8-8359-0c796f55bf07.png)

(je compte effectivement 10 résultats sur la page)

**Comment by raf64flo** [comment]
Ok, en bidouillant le nombre de résultats par page en effet, y'a un bug.

Par contre cette issue est redondante avec  #12, je ferme.
