### ISSUE TITLE
[UI] add example giving text-mining resulits

### ISSUE THREAD

**Issue by jibe-b** [gnpis/DataSearch#3]
Adding a link launching a query for a Wheat phenotype with text-mining annotations returned in the first ten results to

![capture d ecran de 2017-07-28 17-23-40](https://user-images.githubusercontent.com/6146483/28724220-954c89a6-73b9-11e7-988a-e4a6e9ab2761.png)

would provide an entry point similar to the already existing ones.

One possible example is "Mildew".

**Comment by florian-philippe** [comment]
Done. 
Effectif au prochain redéploiement sur la beta.

**Comment by jibe-b** [comment]
Super!
