### ISSUE TITLE
champ source cliquable vers AlvisIR (DOI + terme recherché)

### ISSUE THREAD

**Issue by florian-philippe** [gnpis/DataSearch#4]
![example](https://user-images.githubusercontent.com/9723490/29022123-51af8e4e-7b68-11e7-9d70-9474a3b2499f.png)

Usage de l'API REST d'AlvisIR
Pour la requête "Pm2 pmid=10.1556/CRC.34.2006.4.268" (requête sur le terme Pm2 dans le document ayant le DOI indiqué – l'usage de pmid est erronée et changera prochainement),
La requête à passer est :
http://bibliome.jouy.inra.fr/demo/wheat/alvisir/webapi/search?q=Pm2+pmid%3D10.1556%2FCRC.34.2006.4.268
L'API est simple avec un champ de requête (q) avec pour forme la plus générale : "(<GnPIS_query>) AND (pmid=<DOI1> OR <DOI2>)". La requête doit être encodée (au moins les espaces remplacés par des +).
Une ébauche de spec Swagger est dispo ici http://genome.jouy.inra.fr/~jbbohuon/swagger-ui/dist/index.html

**Comment by florian-philippe** [comment]
Première version : 
Ajout d'un champ source cliquable vers AlvisIR (uniquement DOI) car il est stocké spécifiquement dans un champ db_id et beaucoup plus facile à récupérer côté interface.
-> http://bibliome.jouy.inra.fr/demo/wheat/alvisir/webapi/search?q=pmid%3D10.1556%2FCRC.34.2006.4.268 
(utilisation de la classe UriUtils pour encoder l'URL).

**Comment by raf64flo** [comment]
C'est en prod depuis l'automne dernier.
