### ISSUE TITLE
[surlignement] le surligenement a un problème

### ISSUE THREAD

**Issue by jibe-b** [gnpis/DataSearch#6]
Les balises sont à nouveau affichées en clair.

exemple :

https://urgi.versailles.inra.fr/beta/wheatis/#result/term=Mildew

**Comment by florian-philippe** [comment]
![exemple-mildew](https://user-images.githubusercontent.com/9723490/31218342-4fe2199e-a9ba-11e7-943b-fa0c4655d55d.png)
Je n'ai pas ce soucis dans les devs que je suis entrain de mettre en place.
La version qui est en beta ne semble pas à jour avec les devs en cours.
Une fois que le centrage sera stable, nous ferons un redéploiement sur la beta.

**Comment by jibe-b** [comment]
Ok, merci.

**Comment by raf64flo** [comment]
Utilise plutôt cette URL pour accéder à la version en beta : 
https://urgi.versailles.inra.fr/beta/wheatis-gwt/#result/term=mildew%20openminted

**Comment by jibe-b** [comment]
Ah, ok, excuse-moi j'avais oublié le gwt
